# Generated by Django 6.0.4 on 2026-04-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usergame_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('single', 'Singleplayer'), ('online', 'Online'), ('coop', 'Co-op')], default='single', max_length=10),
        ),
    ]
